# Header
menu:
  首页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  我的博客www.hsblogs.com: http://www.hsblogs.com
  前端技术博客rongchanghai.github.io: https://rongchanghai.github.io/ 

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: haoshuai6-github-io

# Baidu share
baidushare: true